"""DB creation

Revision ID: 5d1de52c0bef
Revises: 
Create Date: 2024-05-07 13:04:08.602425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d1de52c0bef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stepOfDevelopment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fileName', sa.String(), nullable=False),
    sa.Column('analyze_id', sa.String(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stage'], ['stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('stage')
    # ### end Alembic commands ###
