version: "3.7"
services:

  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    hostname: db

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - 5672:5672
      - 15674:15672
    hostname: rabbitmq

  minio:
      image: minio/minio
      ports:
        - 127.0.0.1:9000:9000
        - 9001:9001
      environment:
        - MINIO_ROOT_USER=Simon
        - MINIO_ROOT_PASSWORD=password
      hostname: minio
      command: server /data --console-address ":9001"

  handler:
    image: 3010202/hand_app:latest
    env_file:
      - .env
    command: ["/handler_app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
      - minio

  executor:
    image: 3010202/exec_app:latest
    command: ["/exec_app/docker/exec.sh"]
    ports:
      - 8001:8001
    depends_on:
      - rabbitmq
      - minio
      - db
    restart: always

